/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsNewAccountRouteImport } from './routes/accounts/new-account'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewAccountRoute = AccountsNewAccountRouteImport.update({
  id: '/accounts/new-account',
  path: '/accounts/new-account',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/new-account': typeof AccountsNewAccountRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/new-account': typeof AccountsNewAccountRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/new-account': typeof AccountsNewAccountRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accounts/new-account'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accounts/new-account'
  id: '__root__' | '/' | '/accounts/new-account'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsNewAccountRoute: typeof AccountsNewAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new-account': {
      id: '/accounts/new-account'
      path: '/accounts/new-account'
      fullPath: '/accounts/new-account'
      preLoaderRoute: typeof AccountsNewAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsNewAccountRoute: AccountsNewAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
