/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InboxRouteImport } from './routes/_inbox'
import { Route as InboxIndexRouteImport } from './routes/_inbox/index'
import { Route as AccountsNewRouteImport } from './routes/accounts/new'
import { Route as InboxEmailEmailIdRouteImport } from './routes/_inbox/email.$emailId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/_inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxEmailEmailIdRoute = InboxEmailEmailIdRouteImport.update({
  id: '/email/$emailId',
  path: '/email/$emailId',
  getParentRoute: () => InboxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/': typeof InboxIndexRoute
  '/email/$emailId': typeof InboxEmailEmailIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/': typeof InboxIndexRoute
  '/email/$emailId': typeof InboxEmailEmailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_inbox': typeof InboxRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/accounts/new': typeof AccountsNewRoute
  '/_inbox/': typeof InboxIndexRoute
  '/_inbox/email/$emailId': typeof InboxEmailEmailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/settings'
    | '/accounts/new'
    | '/'
    | '/email/$emailId'
  fileRoutesByTo: FileRoutesByTo
  to: '/onboarding' | '/settings' | '/accounts/new' | '/' | '/email/$emailId'
  id:
    | '__root__'
    | '/_inbox'
    | '/onboarding'
    | '/settings'
    | '/accounts/new'
    | '/_inbox/'
    | '/_inbox/email/$emailId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InboxRoute: typeof InboxRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  AccountsNewRoute: typeof AccountsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inbox': {
      id: '/_inbox'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inbox/': {
      id: '/_inbox/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_inbox/email/$emailId': {
      id: '/_inbox/email/$emailId'
      path: '/email/$emailId'
      fullPath: '/email/$emailId'
      preLoaderRoute: typeof InboxEmailEmailIdRouteImport
      parentRoute: typeof InboxRoute
    }
  }
}

interface InboxRouteChildren {
  InboxIndexRoute: typeof InboxIndexRoute
  InboxEmailEmailIdRoute: typeof InboxEmailEmailIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIndexRoute: InboxIndexRoute,
  InboxEmailEmailIdRoute: InboxEmailEmailIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  InboxRoute: InboxRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  AccountsNewRoute: AccountsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
